# Generated by Django 6.0.4 on 2026-04-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blockedkeyword_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('matched_keyword', models.CharField(blank=True, max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='api.childdevice')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
